--------------------------------------------------------
--  Fichier créé - jeudi-juin-11-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AGENT
--------------------------------------------------------

  CREATE TABLE "AHMED"."AGENT" 
   (	"CIN" VARCHAR2(8 BYTE), 
	"NOM" VARCHAR2(10 BYTE), 
	"PRENOM" VARCHAR2(10 BYTE), 
	"MDP" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AHMED.AGENT
SET DEFINE OFF;
Insert into AHMED.AGENT (CIN,NOM,PRENOM,MDP) values ('1547563','jaje','ahmed','Langue1233');
Insert into AHMED.AGENT (CIN,NOM,PRENOM,MDP) values ('1234','jspsjp','jejjar','zakekakr');
--------------------------------------------------------
--  DDL for Index UNIQUECIN
--------------------------------------------------------

  CREATE UNIQUE INDEX "AHMED"."UNIQUECIN" ON "AHMED"."AGENT" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AGENT
--------------------------------------------------------

  ALTER TABLE "AHMED"."AGENT" ADD CONSTRAINT "UNIQUECIN" UNIQUE ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AHMED"."AGENT" MODIFY ("MDP" NOT NULL ENABLE);
  ALTER TABLE "AHMED"."AGENT" MODIFY ("CIN" NOT NULL ENABLE);
