--------------------------------------------------------
--  Fichier créé - lundi-avril-06-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONTENIR
--------------------------------------------------------

  CREATE TABLE "SELIM"."CONTENIR" 
   (	"ID_JE" NUMBER, 
	"NOM_EQ" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPE
--------------------------------------------------------

  CREATE TABLE "SELIM"."EQUIPE" 
   (	"NOM_EQUIPE" VARCHAR2(100 BYTE), 
	"TOTAL_JOUEUR" NUMBER, 
	"SCORE" NUMBER, 
	"CATEGORIE" VARCHAR2(100 BYTE), 
	"MANAGER_EQ" VARCHAR2(100 BYTE), 
	"IMAGE_EQUIPE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table JOUEUR
--------------------------------------------------------

  CREATE TABLE "SELIM"."JOUEUR" 
   (	"ID_J" NUMBER(*,0), 
	"NOM" VARCHAR2(30 BYTE), 
	"PRENOM" VARCHAR2(30 BYTE), 
	"POIDS" FLOAT(126), 
	"TAILLE" FLOAT(126), 
	"NUMERO" NUMBER, 
	"DATE_NAISSANCE" DATE, 
	"IMAGE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SELIM.CONTENIR
SET DEFINE OFF;
Insert into SELIM.CONTENIR (ID_JE,NOM_EQ) values ('45834','Barcelone');
Insert into SELIM.CONTENIR (ID_JE,NOM_EQ) values ('37582','Real Madrid');
REM INSERTING into SELIM.EQUIPE
SET DEFINE OFF;
Insert into SELIM.EQUIPE (NOM_EQUIPE,TOTAL_JOUEUR,SCORE,CATEGORIE,MANAGER_EQ,IMAGE_EQUIPE) values ('Real Madrid','1','8','Football','Zinedine Zidane','C:/Users/selim/Projet c++/images_projet/gettyimages-89416970-594x594.jpg');
Insert into SELIM.EQUIPE (NOM_EQUIPE,TOTAL_JOUEUR,SCORE,CATEGORIE,MANAGER_EQ,IMAGE_EQUIPE) values ('Barcelone','1','15','Football','Quique Setien','C:/Users/selim/Projet c++/images_projet/unnamed.png');
REM INSERTING into SELIM.JOUEUR
SET DEFINE OFF;
Insert into SELIM.JOUEUR (ID_J,NOM,PRENOM,POIDS,TAILLE,NUMERO,DATE_NAISSANCE,IMAGE) values ('37582','Eden','Hazard','74','1,75','10',to_date('07/01/91','DD/MM/RR'),'C:/Users/selim/Projet c++/images_projet/eden.jpg');
Insert into SELIM.JOUEUR (ID_J,NOM,PRENOM,POIDS,TAILLE,NUMERO,DATE_NAISSANCE,IMAGE) values ('45834','Messi','Lionel','59','1,7','10',to_date('24/06/87','DD/MM/RR'),'C:/Users/selim/Projet c++/images_projet/messi.jpg');
--------------------------------------------------------
--  DDL for Index PK_NOM_EQUIPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "SELIM"."PK_NOM_EQUIPE" ON "SELIM"."EQUIPE" ("NOM_EQUIPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CONTENIR
--------------------------------------------------------

  CREATE UNIQUE INDEX "SELIM"."PK_CONTENIR" ON "SELIM"."CONTENIR" ("ID_JE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table JOUEUR
--------------------------------------------------------

  ALTER TABLE "SELIM"."JOUEUR" ADD PRIMARY KEY ("ID_J")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SELIM"."JOUEUR" MODIFY ("NUMERO" NOT NULL ENABLE);
  ALTER TABLE "SELIM"."JOUEUR" MODIFY ("TAILLE" NOT NULL ENABLE);
  ALTER TABLE "SELIM"."JOUEUR" MODIFY ("POIDS" NOT NULL ENABLE);
  ALTER TABLE "SELIM"."JOUEUR" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "SELIM"."JOUEUR" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPE
--------------------------------------------------------

  ALTER TABLE "SELIM"."EQUIPE" MODIFY ("IMAGE_EQUIPE" NOT NULL ENABLE);
  ALTER TABLE "SELIM"."EQUIPE" ADD CONSTRAINT "PK_NOM_EQUIPE" PRIMARY KEY ("NOM_EQUIPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SELIM"."EQUIPE" MODIFY ("MANAGER_EQ" NOT NULL ENABLE);
  ALTER TABLE "SELIM"."EQUIPE" MODIFY ("CATEGORIE" NOT NULL ENABLE);
  ALTER TABLE "SELIM"."EQUIPE" MODIFY ("SCORE" NOT NULL ENABLE);
  ALTER TABLE "SELIM"."EQUIPE" MODIFY ("TOTAL_JOUEUR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTENIR
--------------------------------------------------------

  ALTER TABLE "SELIM"."CONTENIR" ADD CONSTRAINT "PK_CONTENIR" PRIMARY KEY ("ID_JE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SELIM"."CONTENIR" MODIFY ("NOM_EQ" NOT NULL ENABLE);
  ALTER TABLE "SELIM"."CONTENIR" MODIFY ("ID_JE" NOT NULL ENABLE);
