--------------------------------------------------------
--  Fichier créé - vendredi-juin-12-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AGENTS
--------------------------------------------------------

  CREATE TABLE "Sportify"."AGENTS" 
   (	"CIN" VARCHAR2(8 BYTE), 
	"NOM" VARCHAR2(250 BYTE), 
	"PRENOM" VARCHAR2(250 BYTE), 
	"MDP" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CONTENIR
--------------------------------------------------------

  CREATE TABLE "Sportify"."CONTENIR" 
   (	"ID_JE" VARCHAR2(26 BYTE), 
	"NOM_EQ" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "Sportify"."EMPLOYES" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(250 BYTE), 
	"PRENOM" VARCHAR2(250 BYTE), 
	"AGE" NUMBER, 
	"SALAIRE" FLOAT(126), 
	"POST" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPE
--------------------------------------------------------

  CREATE TABLE "Sportify"."EQUIPE" 
   (	"NOM_EQUIPE" VARCHAR2(26 BYTE), 
	"TOTAL_JOUEUR" NUMBER(38,0), 
	"SCORE" NUMBER(38,0), 
	"CATEGORIE" VARCHAR2(26 BYTE), 
	"MANAGER_EQ" VARCHAR2(26 BYTE), 
	"IMAGE_EQUIPE" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPEMENTS
--------------------------------------------------------

  CREATE TABLE "Sportify"."EQUIPEMENTS" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(250 BYTE), 
	"QUANTITE" NUMBER, 
	"IMAGE" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENTS
--------------------------------------------------------

  CREATE TABLE "Sportify"."EVENTS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"BUDGET" VARCHAR2(20 BYTE), 
	"GOAL" VARCHAR2(20 BYTE), 
	"DATE1" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"GUESTLIST" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEURS
--------------------------------------------------------

  CREATE TABLE "Sportify"."FOURNISSEURS" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(250 BYTE), 
	"ADRESSE" VARCHAR2(250 BYTE), 
	"LOGO" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GUESTS
--------------------------------------------------------

  CREATE TABLE "Sportify"."GUESTS" 
   (	"ID" VARCHAR2(20 BYTE), 
	"CONTACTS" VARCHAR2(20 BYTE), 
	"LEVEL_OF_IMPORTANCE" VARCHAR2(255 BYTE), 
	"NAME" VARCHAR2(255 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"JOB" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table JOUEUR
--------------------------------------------------------

  CREATE TABLE "Sportify"."JOUEUR" 
   (	"ID_J" NUMBER(38,0), 
	"NOM" VARCHAR2(26 BYTE), 
	"PRENOM" VARCHAR2(26 BYTE), 
	"POIDS" NUMBER(38,0), 
	"TAILLE" NUMBER(38,1), 
	"NUMERO" NUMBER(38,0), 
	"DATE_NAISSANCE" DATE, 
	"IMAGE" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATCHS
--------------------------------------------------------

  CREATE TABLE "Sportify"."MATCHS" 
   (	"ID" NUMBER(38,0), 
	"HOME_TEAM" VARCHAR2(26 BYTE), 
	"VISITOR_TEAM" VARCHAR2(26 BYTE), 
	"LOCATION" VARCHAR2(26 BYTE), 
	"PLAY_DATE" VARCHAR2(26 BYTE), 
	"HOME_TEAM_PIC" VARCHAR2(128 BYTE), 
	"AWAY_TEAM_PIC" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARTENAIRE
--------------------------------------------------------

  CREATE TABLE "Sportify"."PARTENAIRE" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"CIN" VARCHAR2(8 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"DONS" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPLAYS
--------------------------------------------------------

  CREATE TABLE "Sportify"."REPLAYS" 
   (	"ID" NUMBER(38,0), 
	"TITLE" VARCHAR2(256 BYTE), 
	"THUMBNAIL_PATH" VARCHAR2(256 BYTE), 
	"VIDEO_PATH" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table STADES
--------------------------------------------------------

  CREATE TABLE "Sportify"."STADES" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(250 BYTE), 
	"LOCALISATION" VARCHAR2(250 BYTE), 
	"NBEMPLOYE" NUMBER, 
	"CAPACITE" NUMBER, 
	"FIELD_SIZE" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TOURNOIS
--------------------------------------------------------

  CREATE TABLE "Sportify"."TOURNOIS" 
   (	"ID" NUMBER(38,0), 
	"NOM" VARCHAR2(26 BYTE), 
	"CATEGORIE" VARCHAR2(26 BYTE), 
	"DATE_LANCEMENT" VARCHAR2(20 BYTE), 
	"NB_PARTICIPANTS" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "Sportify"."USERS" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(250 BYTE), 
	"PRENOM" VARCHAR2(250 BYTE), 
	"MAIL" VARCHAR2(250 BYTE), 
	"USERNAME" VARCHAR2(250 BYTE), 
	"PASSWORD" VARCHAR2(250 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into "Sportify".AGENTS
SET DEFINE OFF;
Insert into "Sportify".AGENTS (CIN,NOM,PRENOM,MDP) values ('12345678','Yassine','Ben Azizi','123');
REM INSERTING into "Sportify".CONTENIR
SET DEFINE OFF;
REM INSERTING into "Sportify".EMPLOYES
SET DEFINE OFF;
REM INSERTING into "Sportify".EQUIPE
SET DEFINE OFF;
Insert into "Sportify".EQUIPE (NOM_EQUIPE,TOTAL_JOUEUR,SCORE,CATEGORIE,MANAGER_EQ,IMAGE_EQUIPE) values ('Barcelona','4','20','gz','gzr',null);
Insert into "Sportify".EQUIPE (NOM_EQUIPE,TOTAL_JOUEUR,SCORE,CATEGORIE,MANAGER_EQ,IMAGE_EQUIPE) values ('Club Africain','4','20','ge','gtrz',null);
REM INSERTING into "Sportify".EQUIPEMENTS
SET DEFINE OFF;
Insert into "Sportify".EQUIPEMENTS (ID,NOM,QUANTITE,IMAGE) values ('1','jeyje','4','C:/Users/toshiba/Pictures/Nouvelle image (16).bmp');
Insert into "Sportify".EQUIPEMENTS (ID,NOM,QUANTITE,IMAGE) values ('2','   gzrgzfz','5','C:/Users/toshiba/Pictures/Copie de Nouvelle image (103).bmp');
REM INSERTING into "Sportify".EVENTS
SET DEFINE OFF;
REM INSERTING into "Sportify".FOURNISSEURS
SET DEFINE OFF;
REM INSERTING into "Sportify".GUESTS
SET DEFINE OFF;
REM INSERTING into "Sportify".JOUEUR
SET DEFINE OFF;
REM INSERTING into "Sportify".MATCHS
SET DEFINE OFF;
Insert into "Sportify".MATCHS (ID,HOME_TEAM,VISITOR_TEAM,LOCATION,PLAY_DATE,HOME_TEAM_PIC,AWAY_TEAM_PIC) values ('41','           gtez','raga','grag','11/06/2020',null,null);
Insert into "Sportify".MATCHS (ID,HOME_TEAM,VISITOR_TEAM,LOCATION,PLAY_DATE,HOME_TEAM_PIC,AWAY_TEAM_PIC) values ('42','Club Africain','Barcelona',null,'12/06/2020','../images_projet/exclamation_mark.png','../images_projet/exclamation_mark.png');
Insert into "Sportify".MATCHS (ID,HOME_TEAM,VISITOR_TEAM,LOCATION,PLAY_DATE,HOME_TEAM_PIC,AWAY_TEAM_PIC) values ('43','Club Africain','Barcelona','     tgaagrt','12/06/2020','../images_projet/exclamation_mark.png','../images_projet/exclamation_mark.png');
REM INSERTING into "Sportify".PARTENAIRE
SET DEFINE OFF;
Insert into "Sportify".PARTENAIRE (NOM,CIN,ADRESSE,DONS) values ('Yassine','12345678','Ariana','1.000.000.000');
REM INSERTING into "Sportify".REPLAYS
SET DEFINE OFF;
Insert into "Sportify".REPLAYS (ID,TITLE,THUMBNAIL_PATH,VIDEO_PATH) values ('41','Match','C:/Users/toshiba/Pictures/Nouvelle image (10).bmp','C:/Users/toshiba/Desktop/Sportify/Integration/images_projet/LiverpoolvsManchesterCity.mp4');
REM INSERTING into "Sportify".STADES
SET DEFINE OFF;
REM INSERTING into "Sportify".TOURNOIS
SET DEFINE OFF;
REM INSERTING into "Sportify".USERS
SET DEFINE OFF;
Insert into "Sportify".USERS (ID,NOM,PRENOM,MAIL,USERNAME,PASSWORD) values ('1','Yassine','Ben Azizi','suckadick@gmail.fuck','Sumpark','123456789');
--------------------------------------------------------
--  DDL for Index AGENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "Sportify"."AGENTS_PK" ON "Sportify"."AGENTS" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "Sportify"."EMPLOYES_PK" ON "Sportify"."EMPLOYES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EQUIPEMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "Sportify"."EQUIPEMENTS_PK" ON "Sportify"."EQUIPEMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEURS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "Sportify"."FOURNISSEURS_PK" ON "Sportify"."FOURNISSEURS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index JOUEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "Sportify"."JOUEUR_PK" ON "Sportify"."JOUEUR" ("ID_J") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARTENAIRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "Sportify"."PARTENAIRE_PK" ON "Sportify"."PARTENAIRE" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REPLAYS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "Sportify"."REPLAYS_PK" ON "Sportify"."REPLAYS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index STADES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "Sportify"."STADES_PK" ON "Sportify"."STADES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "Sportify"."TABLE1_PK" ON "Sportify"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger EMPLOYES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "Sportify"."EMPLOYES_TRG" 
BEFORE INSERT ON "Sportify".EMPLOYES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT EMPLOYES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "Sportify"."EMPLOYES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EQUIPEMENTS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "Sportify"."EQUIPEMENTS_TRG" 
BEFORE INSERT ON "Sportify".EQUIPEMENTS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT EQUIPEMENTS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "Sportify"."EQUIPEMENTS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FOURNISSEURS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "Sportify"."FOURNISSEURS_TRG" 
BEFORE INSERT ON "Sportify".FOURNISSEURS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT FOURNISSEURS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "Sportify"."FOURNISSEURS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MATCHS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "Sportify"."MATCHS_TRG" 
BEFORE INSERT ON "Sportify".MATCHS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT MATCHS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "Sportify"."MATCHS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REPLAYS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "Sportify"."REPLAYS_TRG" 
BEFORE INSERT ON "Sportify".REPLAYS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "Sportify"."REPLAYS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger STADES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "Sportify"."STADES_TRG" 
BEFORE INSERT ON "Sportify".STADES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT STADES_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "Sportify"."STADES_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TOURNOIS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "Sportify"."TOURNOIS_TRG" 
BEFORE INSERT ON "Sportify".TOURNOIS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT TOURNOIS_SEQ1.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "Sportify"."TOURNOIS_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USERS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "Sportify"."USERS_TRG" 
BEFORE INSERT ON "Sportify".USERS 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT USERS_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "Sportify"."USERS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table AGENTS
--------------------------------------------------------

  ALTER TABLE "Sportify"."AGENTS" ADD CONSTRAINT "AGENTS_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "Sportify"."AGENTS" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "Sportify"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "Sportify"."EMPLOYES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPEMENTS
--------------------------------------------------------

  ALTER TABLE "Sportify"."EQUIPEMENTS" ADD CONSTRAINT "EQUIPEMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "Sportify"."EQUIPEMENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEURS
--------------------------------------------------------

  ALTER TABLE "Sportify"."FOURNISSEURS" ADD CONSTRAINT "FOURNISSEURS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "Sportify"."FOURNISSEURS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GUESTS
--------------------------------------------------------

  ALTER TABLE "Sportify"."GUESTS" MODIFY ("CONTACTS" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JOUEUR
--------------------------------------------------------

  ALTER TABLE "Sportify"."JOUEUR" ADD CONSTRAINT "JOUEUR_PK" PRIMARY KEY ("ID_J")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "Sportify"."JOUEUR" MODIFY ("ID_J" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARTENAIRE
--------------------------------------------------------

  ALTER TABLE "Sportify"."PARTENAIRE" MODIFY ("CIN" NOT NULL ENABLE);
  ALTER TABLE "Sportify"."PARTENAIRE" ADD CONSTRAINT "PARTENAIRE_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPLAYS
--------------------------------------------------------

  ALTER TABLE "Sportify"."REPLAYS" ADD CONSTRAINT "REPLAYS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "Sportify"."REPLAYS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STADES
--------------------------------------------------------

  ALTER TABLE "Sportify"."STADES" ADD CONSTRAINT "STADES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "Sportify"."STADES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "Sportify"."USERS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "Sportify"."USERS" MODIFY ("ID" NOT NULL ENABLE);
